# Application
spring.application.name=agricultural-blockchain
server.port=8888

# MySQL Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/blockchaindb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3307/blockdb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# URL de base pour la vérification des produits
app.verification.url=http://localhost:8888/api/blockchain
